name: Tests

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure git
        run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'

      - name: Install Dependencies
        working-directory: ./
        run: go mod download

      - name: Run Tests
        working-directory: ./
        run: make test

