name: Build, Lint, and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-20.04
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.47.3
          working-directory: ./pkg
          skip-pkg-cache: true
          skip-build-cache: true
          args: -E gofmt --timeout=5m

      - name: Run Tests
        run: make test
